config/routes.rb
BPlugged::Application.routes.draw do
  get "categories/show"

  get "home/index"

  root :to => 'plugins#index'

  resources :authors
  resources :categories
  resources :plugins

  match 'about' => 'home#about', :as => :about
  match 'faq' => 'home#faq', :as => :faq
  match 'contact' => 'home#contact', :as => :contact

end

app/models/author.rb
class Author < ActiveRecord::Base
  attr_accessible :name

  has_and_belongs_to_many :plugins

  default_scope :order => "name ASC"

  def to_param
  	name
  end
end

app/models/build.rb
class Build < ActiveRecord::Base
  attr_accessible :name

  has_and_belongs_to_many :plugin_files
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :name, :slug, :custom_name

  has_and_belongs_to_many :plugins

  default_scope :order => "name ASC"

  # Specify the slug as the link URL
  def to_param
  	slug
  end
end

app/models/plugin.rb
class Plugin < ActiveRecord::Base
  attr_accessible :banner, :downloads, :name, :slug, :stage, :summary

  has_and_belongs_to_many :categories
  has_and_belongs_to_many :authors
  has_many :plugin_files
  has_many :builds, :through => :plugin_files

  def to_param
  	slug
  end

  def self.search(page = 1, sort = nil, category = nil, author = nil, title = nil)
    condition = []
    args = {}
    cat = nil
    plugins = self

    # Start with a base of the categories plugins if defined
    if not category.nil? and not category.empty? and not category == '-1'
      cat = Category.find_by_slug(category)
      plugins = cat.plugins if not cat.nil?
    end

    # Find all plugins by the author, create an array of their IDs. This is to make sure all authors show up for plugins.
    if not author.nil? and not author.empty?
      plugin_ids = plugins.all(:joins => :authors, :conditions => ['lower(authors.name) LIKE ?', "%#{author.downcase}%"]).map(&:id)
      condition.push 'plugins.id in (:plugin_ids)'
      args[:plugin_ids] = plugin_ids
    end

    # Add the title to the arguments if required
    if not title.nil? and not title.empty?
      condition.push 'lower(plugins.name) LIKE :title'
      args[:title] = "%#{title.downcase}%"
    end

    #Join the conditions and find all the required plugins
    conditions = condition.join(" AND ")
    plugins = plugins.paginate(:page => page, :per_page => 20).all(:include => [:categories, :authors, {:plugin_files => :builds}], :conditions => [conditions, args], :order => sort)

    return plugins
  end
end

app/models/plugin_file.rb
class PluginFile < ActiveRecord::Base
  attr_accessible :changelog, :download_count, :download_url, :filename, :md5_sum, :name, :size, :status, :type, :uploaded

  belongs_to :plugin
  has_and_belongs_to_many :builds

  default_scope :order => "uploaded DESC"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :init

  def init
  	@start_time = Time.now.usec
  	@categories = Category.all
  	@current_action = action_name
  	@current_controller = controller_name
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  include PluginSort
  def show
  	@author = Author.find(:first, :conditions => ['lower(name) = ?', params[:id].downcase ], :include => :plugins)
  	if not @author.nil?
    	@plugins = @author.plugins.paginate(:page => params[:page], :per_page => 20).all(:include => [:plugin_files, :authors, :categories, :builds], :order => "#{sort_column} #{sort_direction}") || []
    else
    	@plugins = []
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @plugins }
    end
  end
  def index

  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include PluginSort
  def show
  	@plugins = Category.find_by_slug(params[:id], :include => :plugins).plugins.paginate(:page => params[:page], :per_page => 20).all(:include => [:plugin_files, :authors, :categories, :builds], :order => "#{sort_column} #{sort_direction}")

  	respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @plugins }
  	end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @plugins = Plugin.page(params[:page]).per_page(20).order('last_updated DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @plugins }
    end
  end
end

app/controllers/plugins_controller.rb
class PluginsController < ApplicationController
  include PluginSort
  def index
  	# Search params
  	page = params[:page]
  	sort = "#{sort_column} #{sort_direction}"
  	category = params[:category]
  	author = params[:author]
  	title = params[:title]
  	if not (category.nil? && author.nil? && title.nil?)
    	@plugins = Plugin.search(page, sort, category, author, title)
    else
    	@plugins = Plugin.paginate(:page => params[:page], :per_page => 20).all(:include => [:categories, :authors, {:plugin_files => :builds}], :order => sort)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @plugins }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/plugins_helper.rb
module PluginsHelper
  include PluginSort
  def getBuilds(plugin)
    return [] if plugin.plugin_files.first.nil?
    return plugin.plugin_files.first.builds
  end

  def getLatestBuild(plugin)
    return '' if plugin.plugin_files.first.nil?
    return '' if plugin.plugin_files.first.builds.first.nil?
    return "(#{plugin.plugin_files.first.builds.first.name})"
  end

  def getLatestDownload(plugin)
    return '' if plugin.plugin_files.first.nil?
    return link_to plugin.plugin_files.first.name, plugin.plugin_files.first.download_url
  end

  def sortable(column, title = nil, default_sort = "asc")
    title ||= column.titleize
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil
    if column != sort_column then
      direction = default_sort
    else
      direction = (sort_direction == "asc") ? "desc" : "asc"
    end
	options = {:sort => column, :dir => direction}
    link_to title, params.merge(options), {:class => css_class}
  end
end

app/views/authors/show.html.erb
<div class="row-fluid">
  <div class="span12">  
    <h1>BukkitDev Profile: <%= link_to @author.name, 'http://dev.bukkit.org/profiles/' + @author.name %></h1>
  </div>
</div>
<%= render "shared/plugin_list" %>

app/views/categories/show.html.erb
<%= render "shared/plugin_list" %>

app/views/home/about.html.erb
<div class="row-fluid"><div class="span12 info">
	<h1>About</h1>
	<div class="well">
		<p>Modd.in is a Bukkit Plugin search engine written and run by me, Steven Scott.
		I'm hoping in the future to expand it to a search engine for more game modifications, as well as a hosting platform for plugins and modifications.</p>

		<p>The Modd.in website is open source, and the code is available on BitBucket at: <a href="https://bitbucket.org/drakia/bplugged">https://bitbucket.org/drakia/bplugged</a></p>

		<p>Modd.in was born out of the need for a quality centralized search system for Bukkit plugins. The Curse search framework just was not up to par for my liking, and the plugin search hosted by Bukkit, though usable, had its issues.</p>
		
		<p>If you find any bugs, or run into issues with the site, please report them at <a href="mailto:Moddin@thedgtl.net">ModdIn@TheDgtl.net</a></p>
	</div>
</div></div>

app/views/home/contact.html.erb
<div class="row-fluid"><div class="span12 info">
	<h1>Contact</h1>
	<div class="well">
		<h2>Want to get in touch?</h2>
		<p>If you have any questions, concerns, or suggestions please feel free to contact me via email at <a href="mailto:Moddin@thedgtl.net">ModdIn@TheDgtl.net</a></p>
	</div>
</div></div>

app/views/home/faq.html.erb
<div class="row-fluid"><div class="span12 info">
	<h1>F.A.Q</h1>
	<div class="well">
		<b>Why was the layout changed/site rewritten?</b>
		<hr>
		The previous layout was always supposed to just be temporary. I decided to rewrite the site in Ruby on Rails as a learning experience. I also wrote a new scraper from scratch in Ruby, as BukGet had a tendency to return invalid/incorrect/incomplete results.
	</div><div class="well">
		<b>Why does the site now contain ads?</b>
		<hr>
		Sadly running a website like this isn't free. I'm running ads to see what kind of income it will supply, and to hopefully offset the cost of hosting and the domain.
	</div><div class="well">
		<b>I want to contribute to the site, how do I help?</b>
		<hr>
		If you know how to program, you can always make additions or bug fixes, and submit pull requests on <a href="https://bitbucket.org/drakia/bplugged">BitBucket</a><br />
		If you want to help keep the site running, feel free to donate: [Paypal Link]
	</div><div class="well">
		<b>Why should I use Modd.In instead of BukkitDev for finding plugins?</b>
		<hr>
		Modd.In only searches plugin names, as opposed to the entire plugin description. Most users will find this a good thing as it returns more accurate and useful results. On top of that, download links are available directly from the search results.
	</div>
</div></div>

app/views/home/index.html.erb
<% if will_paginate @plugins %>
    <div class="paginate"><%= will_paginate @plugins %></div>
<% end %>
<table width="100%">
    <tr><th style="width: 100px;">Category</th><th><a href="#Title">Title</a></th><th class="pMin">Author(s)</th><th class="pMin"><a href="#Updated">Last Update</a></th><th class="pSmall">CB Build</th><th class="pSmall">Download</th></tr>

    <%= render @plugins %>
</table>
<% if will_paginate @plugins %>
    <div class="paginate"><%= will_paginate @plugins %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Bukkit.Modd.in - The Bukkit Plugin List and Search Engine</title>
    <link type="application/opensearchdescription+xml" rel="search" href="/search.xml" />
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= csrf_meta_tags %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>

  <body>
    <div class="navbar">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="brand" href="/"><img src="/assets/logo.png" /></a>
        </div>
      </div>
    </div>
    <div class="nav-search">
      <div class="container-fluid">
        <%= form_tag plugins_path, :method => 'get', :class => 'form-inline' do%>
          <%= label_tag :title, "Title: ", :class => 'hide' %><%= text_field_tag :title, params[:title], {:autofocus => "autofocus", :placeholder => 'Title', :class => 'input-medium' } %>
          <%= label_tag :author, "Author: ", :class => 'hide' %><%= text_field_tag :author, params[:author], {:placeholder => 'Author', :class => 'input-medium'} %>
          <%= label_tag :category, "Category: ", :class => 'hide' %>
          <%= select_tag :category, '<option value="-1">All</option>'.html_safe + options_from_collection_for_select(Category.all, :slug, :name, (@current_controller == 'categories') ? params[:id] : params[:category]), {:class => 'hidden-phone'} %>
          <%= submit_tag "Search", :name => nil, :class => 'btn' %>
        <% end %>
        <script type="text/javascript">
        <!--
        document.getElementById("title").focus();
        -->
        </script>
      </div>
    </div>
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span2">
          <div id="toggle-sidebar" class="btn btn-small pull-right">
            <i class="icon-minus"></i>
          </div>
          <div class="well sidebar-nav">
              <ul class="nav nav-list">
                <li class="nav-header">Browse</li>
              </ul>
            <div id="sidebar" class="hidden-phone">
              <ul class="nav nav-list">
                <li <%= @current_controller == 'categories' || (params[:category] && params[:category] != '-1') ? '' : ' class="active"'.html_safe %>><%= link_to "All", Plugin %></li>
                <% @categories.each do |category| %>
                  <li <%= params[:id] == category.slug || params[:category] == category.slug ? ' class="active"'.html_safe : '' %>><%= link_to category.name, category %></li>
                <% end %>
              </ul>
              <hr />
			  <ul class="nav nav-list">
			    <li class="nav-header">Advertisement</li>
				<script type="text/javascript"><!--
				google_ad_client = "ca-pub-6160345314856655";
				/* dgtl_plugin_sidebar */
				google_ad_slot = "5524332721";
				google_ad_width = 160;
				google_ad_height = 600;
				//-->
				</script>
				<script type="text/javascript"
				src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
				</script>
			  </ul>
              <hr />              
              <ul class="nav nav-list">
                <li class="nav-header">Support</li>
                <li><%= link_to 'About', about_url %></li>
                <li><%= link_to 'FAQ', faq_url %></li>
                <li><%= link_to 'Contact Us', contact_url %></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="span10">
          <%= yield %>
        </div>
      </div>
      <div class="row-fluid">
        <div class="span12">
          <div class="footer">Page took <%= sprintf('%.0f', (Time.now.usec - @start_time).abs / 1000.0) %>ms to load</div>
        </div>
      </div>
    </div>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
    <script type="text/javascript">
    $(document).ready(function() {
      $("#toggle-sidebar").click(function() {
        $(this).find('i').toggleClass('icon-plus icon-minus');
        $('#sidebar').toggle().toggleClass('hidden-phone');
      });
    });
    </script>

  </body>
</html>

app/views/plugins/_ad.html.erb
<div class="row-fluid plugins table-bordered">
  <div class="span12 ad">
    <script type="text/javascript"><!--
	google_ad_client = "ca-pub-6160345314856655";
	/* dgtl_plugins */
	google_ad_slot = "3606811789";
	google_ad_width = 728;
	google_ad_height = 90;
	//-->
	</script>
	<script type="text/javascript"
	src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
	</script>
  </div>
</div>

app/views/plugins/_pagination.html.erb
<% if not @plugins.empty? and will_paginate @plugins %>
	<div class="row-fluid">
	  <div class="span12 pagination pagination-centered">
	  	<%= will_paginate @plugins, :renderer => PaginationListLinkRenderer, :next_label => "»", :previous_label => "«" %>
  	</div>
	</div>
<% end %>

app/views/plugins/_plugin.html.erb
<div class="row-fluid plugins table-bordered">
  <div class="span10 description">
    <p>
      <span class="title"><a href="http://dev.bukkit.org/server-mods/<%= plugin.slug %>"><%= plugin.name %></a></span> 
      <span class="author">by 
        <% plugin.authors.each_with_index do |author, index| %>
          <%= link_to author.name, author %><%= ", " if not plugin.authors[index + 1].nil? %>
        <% end %>
      </span> 
      <span class="categories">(
        <% plugin.categories.each_with_index do |category, index| %>
          <%= link_to category.custom_name, category -%>
          <%= "/" if not plugin.categories[index + 1].nil? -%>
        <% end %>
       )</span><br />
      <span class="updated">Updated: <%= plugin.last_updated.to_formatted_s(:long) if not plugin.last_updated.nil? %> / Total Downloads: <%= plugin.downloads %></span>
    </p>
    <p><span class="description">
       <%= plugin.summary[0, 170].html_safe if not plugin.summary.nil? %><%= '...' if (not plugin.summary.nil?) && plugin.summary.length > 170 %>
       <!--<%= link_to '(More)', plugin %>-->
    </span></p>
  </div>
  <div class="span2 download">
    <span><%= getLatestDownload(plugin) %><br /><%= getLatestBuild(plugin) %></span>
  </div>
</div>

app/views/plugins/index.html.erb
<%= render "shared/plugin_list" %>

app/views/shared/_plugin_list.html.erb
<%= render "plugins/pagination" %>
    <% if not @plugins.empty? %>
        <div class="row-fluid">
            <div class="span12 sort">
                Sort: <%= sortable 'name' %> / <%= sortable "last_updated", "Updated", 'desc' %> / <%= sortable 'downloads', 'Downloads', 'desc' %>
            </div>
        </div>
		<% @plugins.each_with_index do |plugin, index| %>
			<%= render "plugins/ad" if index == 10 %>
			<%= render plugin %>
		<% end %>
		<%= render "plugins/ad" if (@plugins.length < 10 || @plugins.length > 15) %>
    <% else %>
      <div class="row-fluid plugins table-bordered">
        <div class="span12 description" style="text-align: center">
          No Plugins Found
        </div>
      </div>
	  <%= render "plugins/ad" %>
    <% end %>
<%= render "plugins/pagination" %>